# This workflow creates a new GitHub Release when a tag is pushed.
# It automatically generates a changelog and can optionally attach assets built by the `build-assets.yml` workflow.

name: Create GitHub Release

on:
  push:
    tags:
      - "v*" # Trigger on tags like v1.0, v1.2.3

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build:
    name: Build Release Assets
    uses: ./.github/workflows/build-assets.yml

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all history for git log

      - name: Download build assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: release-assets

      - name: Create GitHub Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.event.repository.name }} ${{ github.ref_name }}" \
            --generate-notes \
            release-assets/*
